name: 🚀 Build ImmortalWrt
on:
  workflow_dispatch:
    inputs:
      owner:
        description: Repo Owner
        default: immortalwrt
        type: string
      repo:
        description: Repo Name
        default: immortalwrt
        type: string
      branch:
        description: Branch
        default: openwrt-23.05
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses-dev gawk flex bison \
          git python2.7 python3 python3-pip unzip wget curl rsync

      - name: Checkout Current Repo
        uses: actions/checkout@v4

      - name: Checkout ImmortalWrt Source
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.owner }}/${{ inputs.repo }}
          ref: ${{ inputs.branch }}
          path: ImmortalWrt
          fetch-depth: 1

      - name: Copy Config & Script
        run: cp -f .config feeds.conf.default diy.sh ImmortalWrt/

      - name: Run diy.sh
        working-directory: ImmortalWrt
        run: |
          chmod +x diy.sh
          ./diy.sh

      - name: Update & Install Feeds
        working-directory: ImmortalWrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build Firmware
        working-directory: ImmortalWrt
        run: make -j$(nproc) V=s

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Firmware
          path: ImmortalWrt/bin/targets
